# JWT 配置
jwt:
  jwtKey: "****"  # JWT 加密秘钥
  encKey: "****"  # JWT 加密敏感信息秘钥
  timeout: 2592000  # 一个月过期一次

# 中间件配置
middleware:
  allowedOrigins:
    - "*"  # 允许跨域访问的来源地址，例如前端开发服务器地址

log:
  file: "logs/app.log"  # 日志文件路径
  maxSize: 5  # 单个日志文件的最大大小，单位为 MB
  maxBackups: 10  # 保留的旧日志文件数量
  maxAge: 30  # 日志文件的最大保存天数
  compress: false  # 是否压缩旧日志文件

# 请求限流配置(令牌桶算法)
limiter:
  capacity: 100  # 令牌桶容量
  fillInterval: 10 #放置令牌的时间间隔(每秒多少次)
  quantum: 1 #每次放置的令牌数

redis:
  addr: "localhost:6379"
  password: "****"
  db: 0